version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: petmatch_postgres
    restart: always
    environment:
      POSTGRES_DB: petmatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petmatch-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: petmatch_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - petmatch-network
    depends_on:
      - postgres

networks:
  petmatch-network:

volumes:
  postgres_data: